name: Rust CI
run-name: Rust testing build 🚀
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: cargo build && cargo build --release
      - name: Run tests
        run: cargo test --release --verbose
